name: CI
on:
  push:
    branches:
      - main
env:
  ITCH_USERNAME: GAGEUSERNAME
  ITCH_GAME_ID: GAMENAMEHERELOL
  WEBGL_BUILD_PATH: 'Build/WebGL'
jobs:
  Auto_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Fal2022VGDC-TargetPlatform
          restore-keys: |
            Library-Fal2022VGDC-
            Library-
      - name: Build WebGL
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: 
          buildsPath: Build
          targetPlatform: WebGL
      - name: Zip Web Build
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.WEBGL_BUILD_PATH }}/WebGL
          dest: ${{ env.WEBGL_BUILD_PATH }}.zip
      - name: Upload WebGL Zip Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webgl-artifact
          path: ${{ env.WEBGL_BUILD_PATH }}.zip
      - name: Upload WebGL to Itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.ITCH_API_KEY }}
          gameData: ${{ env.WEBGL_BUILD_PATH }}.zip
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: 'webgl'
          