name: CI
on:
  push:
    branches:
      - main
env:
  ITCH_USERNAME: GAGEUSERNAME
  ITCH_GAME_ID: GAMENAMEHERELOL
  WEBGL_BUILD_PATH: 'Build/WebGL'
jobs:
  Auto_Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-Fal2022VGDC-TargetPlatform
          restore-keys: |
            Library-Fal2022VGDC-
            Library-
      - name: Create folder
        run: |
          mkdir -p ${{ env.WEBGL_BUILD_PATH }} && cp -R dist ${{ env.WEBGL_BUILD_PATH }}
          ls ${{ env.WEBGL_BUILD_PATH }}
      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: ${{ env.WEBGL_BUILD_PATH }}/testFile.txt
          FILE_DATA: "TEST FILE CONTENTS"
      - name: Zip Web Build
        uses: vimtor/action-zip@v1
        with:
          files: ${{ env.WEBGL_BUILD_PATH }}
          dest: ${{ env.WEBGL_BUILD_PATH }}.zip
      - name: Upload WebGL Zip Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webgl-artifact
          path: ${{ env.WEBGL_BUILD_PATH }}.zip
      - name: Upload WebGL to Itch
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.ITCH_API_KEY }}
          gameData: ${{ env.WEBGL_BUILD_PATH }}.zip
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildChannel: 'webgl'
          